server:
  port: 8085
spring:
  application:
    name: backend
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

app:
  jwt:
    secret: ${JWT_SECRET} # run openssl rand -base64 32 on git bash and put value on environment variable
    access-token-expiration-ms: 900000      # 15 min
    refresh-token-expiration-ms: 1296000000 # 15 days
  rate-limit:
    login:
      max-failures: 10
      window-seconds: 90 #in normal circumstances, it would be 900 seconds but for practical reasons it is 90
  cors:
    allowed-origins: http://localhost:5173
